### ISSUE TITLE
SIFT not found in debian

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.ip.base#3]
It seems that bob.ip.base.VLFEAT is not created. I have traced it down to the fact that the file
/usr/include/vl/sift.h
is not on our system. 
Maybe the header files of the libvlfeat-dev package (which is installed in the machines) have changed?

**Comment by anjos** [comment]
I don't think so. The version shipped with stock debian does not include the sift implementation - maybe because it is proprietary?

https://github.com/vlfeat/vlfeat/tree/master/vl

**Comment by anjos** [comment]
Yes, see a hint at this discussion: https://lists.debian.org/debian-science/2013/11/msg00033.html

**Comment by siebenkopf** [comment]
With a1cfbf71c1483682596bd80fc73481f8e65f0be3 bob.ip.base now compiles when SIFT is not available.
