### ISSUE TITLE
Cannot compile on Arch Linux

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.ip.base#5]
I am getting this error:

    bob/ip/base/affine.cpp: In function ‘PyObject* PyBobIpBase_scale(PyObject*, PyObject*, PyObject*)’:
    bob/ip/base/affine.cpp:134:26: error: ‘isnan’ was not declared in this scope
       if (!isnan(scale_factor)){
                              ^
    bob/ip/base/affine.cpp:134:26: note: suggested alternatives:
    In file included from /home/amir/miniconda3/envs/_build/gcc/include/c++/complex:44:0,
                     from /home/amir/miniconda3/envs/_build/lib/python2.7/site-packages/bob.blitz-2.0.8-py2.7-linux-x86_64.egg/bob/blitz/include/bob.blitz/cppapi.h:14,
                     from bob/ip/base/main.h:11,
                     from bob/ip/base/affine.cpp:11:
    /home/amir/miniconda3/envs/_build/gcc/include/c++/cmath:632:5: note:   ‘std::isnan’
         isnan(_Tp __x)
         ^
    /home/amir/miniconda3/envs/_build/gcc/include/c++/cmath:632:5: note:   ‘std::isnan’
    In file included from /home/amir/miniconda3/envs/_build/include/boost/lexical_cast/detail/inf_nan.hpp:35:0,
                     from /home/amir/miniconda3/envs/_build/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63,
                     from /home/amir/miniconda3/envs/_build/include/boost/lexical_cast/detail/converter_lexical.hpp:54,
                     from /home/amir/miniconda3/envs/_build/include/boost/lexical_cast/try_lexical_convert.hpp:42,
                     from /home/amir/miniconda3/envs/_build/include/boost/lexical_cast.hpp:32,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/string_parse_tree.hpp:13,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/period_parser.hpp:14,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/date_facet.hpp:23,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/gregorian/gregorian_io.hpp:16,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/gregorian/gregorian.hpp:31,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/posix_time/time_formatters.hpp:12,
                     from /home/amir/miniconda3/envs/_build/include/boost/date_time/posix_time/posix_time.hpp:24,
                     from /home/amir/miniconda3/envs/_build/lib/python2.7/site-packages/bob.core-2.1.0-py2.7-linux-x86_64.egg/bob/core/include/bob.core/logging.h:20,
                     from /home/amir/miniconda3/envs/_build/lib/python2.7/site-packages/bob.core-2.1.0-py2.7-linux-x86_64.egg/bob/core/include/bob.core/api.h:14,
                     from bob/ip/base/main.h:13,
                     from bob/ip/base/affine.cpp:11:
    /home/amir/miniconda3/envs/_build/include/boost/math/special_functions/fpclassify.hpp:592:14: note:   ‘boost::math::isnan’
     inline bool (isnan)(T x)
                  ^
    error: command 'gcc' failed with exit status 1
    Command failed: /bin/bash -x -e /home/amir/git/bob.conda/bob.ip.base/build.sh
    conda build --python=2.7 bob.bio.video  114.84s user 5.11s system 95% cpu 2:05.31 total

**Comment by siebenkopf** [comment]
OK, this seems to be a header-issue. Anyways, checking for ``NaN`` there is not the best solution. I will fix that.
